"""add psychologist profile

Revision ID: 72f394ae944f
Revises: 146899f57633
Create Date: 2025-11-13 11:15:07.456961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72f394ae944f'
down_revision: Union[str, Sequence[str], None] = '146899f57633'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psychologist_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('specialization', sa.String(length=255), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('license_number', sa.String(length=255), nullable=True),
    sa.Column('price_per_hour', sa.Integer(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_psychologist_profiles_user_id'), 'psychologist_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_psychologist_profiles_user_id'), table_name='psychologist_profiles')
    op.drop_table('psychologist_profiles')
    # ### end Alembic commands ###
